version: "3.7"

services:

  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  rooms-gateway:
    build:
      context: rooms-gateway
    depends_on:
      - rabbit
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  trips:
    build:
      context: trips
    depends_on:
      - rabbit
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  hotel-gateway:
    build:
      context: hotel-gateway
    depends_on:
      - rabbit
    ports:
      - "8000:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
